/* DSblock model generated by Dymola from Modelica model Pendulum
 Dymola Version 2017 (64-bit), 2016-06-23 translated this at Sun Nov 20 16:27:44 2016

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    4
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    2
#define NP_    2
#define NPS_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 1207873154
#define NHash2_ 1795018949
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    0
#define SizePre_ 0
#define SizeEq_ 0
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 2
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="Pendulum";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=0;
#define QJacobianCGDef_ 1
DYMOLA_STATIC int QJacobianCG_[7]={2 , 3 , 1 , 3 , 4 , 1 , 2};
DYMOLA_STATIC int QJacobianGC_[9]={
3 , 4 , 1 , 1 , 0 , 0 , 2 , 2 , 0};
DYMOLA_STATIC double QJacobianCD_[5]={0  , 44 , 50 , 66 , 77};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,0) = 1;
#endif
BoundParameterSection
InitialSection
InitialSection
InitialStartSection
InitialSection
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection
DYNX(DYNhelp,0) = sqrtGuarded(sqr(DYNX(X_,0))+sqr(DYNX(X_,1)),"x^2+y^2");
DYNX(DYNhelp,1) = divmacro(1.0,"1.0",DYNX(DYNhelp,0),"sqrt(x^2+y^2)");
DYNX(W_,1) = DYNX(DYNhelp,1)*DYNX(DP_,0)*(DYNX(DYNhelp,0)-1);
DYNX(F_,3) =  -(1+DYNX(W_,1)*DYNX(X_,1));
DYNX(F_,1) = DYNX(X_,3);
DYNX(F_,2) =  -DYNX(W_,1)*DYNX(X_,0);
DYNX(F_,0) = DYNX(X_,2);

AcceptedSection1

AcceptedSection2

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("g", "Gravity", 1, 0.0,0.0,0.0,0,513)
DeclareParameter("k", "Spring Constant", 0, 150, 0.0,0.0,0.0,0,560)
DeclareParameter("m", "Mass", 1, 1.0, 0.0,0.0,0.0,0,560)
DeclareState("x", "", 0, 1.05, 0.0,0.0,0.0,0,560)
DeclareDerivative("der(x)", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("y", "", 1, 0, 0.0,0.0,0.0,0,560)
DeclareDerivative("der(y)", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("vx", "", 2, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("der(vx)", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("vy", "", 3, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("der(vy)", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("F", "", 0.0, 0.0,0.0,0.0,0,512)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_) {
static Real initStore[1];
}
StartDataBlock
EndDataBlock
